baseURL = 'https://otipnavi.github.io'
languageCode = 'en-us'
title = 'Ivan writes'
favicon = 'true'
theme = 'hugo-theme-monochrome'
cleanDestinationDir = 'true'
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    navbar_title = "Ivan writes" # default: site's `title`
    footer = "A Hugo blog. Wonderful theme by kaiiiz." # default: None
    enable_collapsible_toc = 'true' # default: false
    enable_collapsible_changelogs = 'false' # default: false
    hide_navbar_on_scroll = 'true' # true | false, default: true
    author = "Ivan" # default: no author `meta` tag

[outputs]
    home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    id = 'G-S9930MH5BE'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

[param]
  [param.syntax_highlight]
  lib = "builtin" # "builtin" | "prism.js" (default: "builtin")
    [param.syntax_highlight.builtin]
    enable_code_copy = true # default: true
