baseURL = 'https://otipnavi.github.io'
languageCode = 'en-us'
title = 'Ivan writes'
favicon = 'true'
theme = 'hugo-theme-monochrome'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    navbar_title = "Ivan writes" # default: site's `title`
    footer = "Contents written by Ivan. Wonderful theme made by kaiiiz." # default: None
    enable_collapsible_toc = 'true' # default: false
    enable_collapsible_changelogs = 'false' # default: false
    hide_navbar_on_scroll = 'true' # true | false, default: true
    author = "Ivan" # default: no author `meta` tag

[outputs]
    home = ["HTML", "RSS", "JSON"]

