baseURL = 'https://otipnavi.github.io'
languageCode = 'en-us'
title = 'Ivan writes'
favicon = 'false'
theme = 'hugo-theme-monochrome'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

services:
  googleAnalytics:
    id = "G-S9930MH5BE"
