name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0'
#         extended: true

      - name: Setup public
        run: git worktree add -B gh-pages ./otipnavi/public origin/gh-pages

      - name: Clean public
        run: rm -rf ./otipnavi/public/*

      - name: Build
        run: hugo -s otipnavi --baseURL https://github.com/otipnavi/otipnavi.github.io.git --themesDir=../.. --minify --environment production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./otipnavi/public
          publish_branch: gh-pages
